version: "3"
services:
  node:
    container_name: "statusmonitor_node"
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    restart: unless-stopped
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    container_name: "statusmonitor_influxdb"
    ports:
      - "8086:8086"
    volumes:
      - myInfluxVolume:/var/lib/influxdb2
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_ORG=SmartEnergy
      - DOCKER_INFLUXDB_INIT_BUCKET=SmartEnergy
    restart: unless-stopped
