version: "3"
volumes:
  web_data:
    name: myInfluxVolume

services:
  node:
    container_name: "statusmonitor_node"
    build: .
    env_file:
      - .env
    ports:
      - "12345:3333"
    restart: unless-stopped
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    container_name: "statusmonitor_influxdb"
    hostname: influx
    ports:
      - "8086:8086"
    volumes:
      - web_data:/var/lib/influxdb2
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_ORG=SmartEnergy
      - DOCKER_INFLUXDB_INIT_BUCKET=SmartEnergy
    restart: unless-stopped
