version: "3"
services:
  node:
    container_name: "statusmonitor_node"
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    restart: unless-stopped
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    container_name: "statusmonitor_influxdb"
    ports:
      - "8086:8086"
    restart: unless-stopped
